"""
Additional export formats: PDF, EPS, G-code.
All generated from the SVG output.
"""

import re
from pathlib import Path


def svg_to_pdf(svg_path: Path, pdf_path: Path) -> Path:
    """Convert SVG to PDF using svglib + reportlab."""
    from svglib.svglib import svg2rlg
    from reportlab.graphics import renderPDF

    drawing = svg2rlg(str(svg_path))
    if drawing:
        renderPDF.drawToFile(drawing, str(pdf_path))
    return pdf_path


def svg_to_eps(svg_path: Path, eps_path: Path) -> Path:
    """Convert SVG to EPS using svglib + reportlab."""
    from svglib.svglib import svg2rlg
    from reportlab.graphics import renderPS

    drawing = svg2rlg(str(svg_path))
    if drawing:
        renderPS.drawToFile(drawing, str(eps_path))
    return eps_path


def svg_to_gcode(
    svg_path: Path,
    gcode_path: Path,
    feed_rate: int = 1000,
    travel_rate: int = 3000,
    z_up: float = 5.0,
    z_down: float = -1.0,
    scale: float = 0.1,
) -> Path:
    """Convert SVG paths to G-code for CNC machines.

    Produces GRBL-compatible G-code suitable for:
    - CNC routers (wood, acrylic, PCB)
    - Laser engravers (set z_down=0, use M3/M5 for laser on/off)
    - Vinyl cutters
    - Pen plotters

    Args:
        svg_path: Input SVG file
        gcode_path: Output G-code file
        feed_rate: Cutting feed rate in mm/min
        travel_rate: Rapid travel rate in mm/min
        z_up: Safe Z height for travel moves
        z_down: Cutting Z depth (0 for laser, negative for router)
        scale: Scale factor from SVG pixels to mm (0.1 = 3840px -> 384mm)
    """
    from svgpathtools import svg2paths

    paths, _ = svg2paths(str(svg_path))

    lines = [
        "; G-code generated by VectorForge",
        f"; Source: {svg_path.name}",
        f"; Feed: {feed_rate} mm/min, Travel: {travel_rate} mm/min",
        f"; Scale: {scale} (SVG px to mm)",
        "",
        "G21 ; mm mode",
        "G90 ; absolute positioning",
        f"G0 Z{z_up} ; raise to safe height",
        "G0 X0 Y0 ; home",
        "M3 S1000 ; spindle/laser on",
        "",
    ]

    for path_idx, path in enumerate(paths):
        if len(path) == 0:
            continue

        lines.append(f"; Path {path_idx + 1}")

        for seg_idx, segment in enumerate(path):
            # Sample points along the segment
            num_points = max(5, int(segment.length() * scale / 2))
            points = []
            for i in range(num_points + 1):
                t = i / num_points
                pt = segment.point(t)
                x = pt.real * scale
                y = -pt.imag * scale  # Flip Y for CNC coordinate system
                points.append((round(x, 3), round(y, 3)))

            if not points:
                continue

            # Move to start of segment
            if seg_idx == 0:
                lines.append(f"G0 Z{z_up}")
                lines.append(f"G0 X{points[0][0]} Y{points[0][1]} F{travel_rate}")
                lines.append(f"G1 Z{z_down} F{feed_rate // 2}")

            # Cut along points
            for x, y in points[1:]:
                lines.append(f"G1 X{x} Y{y} F{feed_rate}")

        lines.append(f"G0 Z{z_up} ; lift")
        lines.append("")

    lines.extend([
        "M5 ; spindle/laser off",
        f"G0 Z{z_up} ; safe height",
        "G0 X0 Y0 ; return home",
        "M2 ; program end",
    ])

    gcode_path.write_text("\n".join(lines), encoding="utf-8")
    return gcode_path
